### ISSUE TITLE
uninstall not working?

### ISSUE THREAD

**Issue by SerbanC** [vertiginous/pik#126]
Hi,

here are the lines in my console:

**D:\workspace\foo>pik refresh**
INFO: Refreshing the list of installed rubies.

INFO: Adding:  [ruby-]1.9.2[-p136]
      Located at:  C:\Documents and Settings\usr.pik\rubies\ruby-1.9.2-p136\bin

INFO: Adding:  [ruby-]1.9.2-p290
      Located at:  C:\Ruby192\bin

INFO: Adding:  [ruby-]1.8.7-p352
      Located at:  C:\Ruby187\bin

**D:\workspace\foo>pik uninstall 1.9.2**
Are you sure you'd like to uninstall '[ruby-]1.9.2[-p136]versionruby 1.9.2p136 (2010-12-25) [i386-mingw32]
pathC:\Documents and Settings\usr.pik\rubies\ruby-1.9.2-p136\bin'?  |yes|
yes

There was an error.
 Error: undefined method `[]' for nil:NilClass

  in: pik/commands/uninstall_command.rb:18:in `execute'
  in: pik_runner:27

**D:\workspace\foo>pik list**
      ruby-1.8.7-p352
=> ruby-1.9.2-p290
      ruby-1.9.2-p136

**Comment by danielmacho72** [comment]
I had same problem and it turned out I did not installed Pik properly

**This is what I did when it went wrong:**
- Install ChocolateY (https://chocolatey.org/ ) - This is kind of an "apt-get" comand for windows (cinst)
- Install Ruby version using cinst command from chocolate: cinst ruby
- Install Pik using cinst: cinst pik 
- I could successfully add ruby bin folder doing 
   1) **pik add c:\tools\ruby213\bin**
   2) **pik list**
   3) **pik use ruby-2.1.3-p242**
- However when trying to run **pik unin** I got that **undefined method** error message

**This is what I missed and after that I could uninstall properly:**

1) c:\ gem install pik
2) go to  c:\tools\ruby213\lib\ruby\gems\2.1.0\gems\pik-0.2.8\features
3) run  **pik_install c:\tools**
4) after that I went to **c:\tools** and I could successfully run **c:\tools> pik unin**

**Comment by luislavena** [comment]
@SerbanC @danielmacho72 pik is no longer maintained.

Please manually install and uninstall your versions of Ruby and use Uru instead:

https://bitbucket.org/jonforums/uru/
