### ISSUE TITLE
pik_install fails

### ISSUE THREAD

**Issue by ghost** [vertiginous/pik#47]
Using `pik_install` fails with the message:
`Thank you for using pik.`

`C:/Ruby/lib/ruby/gems/1.8/gems/pik-0.2.6/bin/pik_install:12:in 'directory?': can't convert nil into String (TypeError)`

`from C:/Ruby/lib/ruby/gems/1.8/gems/pik-0.2.6/bin/pik_install:12`

`from C:/Ruby/bin/pik_install:19:in 'load'`

`from C:/Ruby/bin/pik_install:19`

Running `pik_install` with the Ruby path, creates the desired result (i.e. `pik` becomes available).

`pik -V`: 0.2.6

`ruby -v`: ruby 1.8.6 (2009-08-04 patchlevel 383) [i386-mingw32]

`ver`: Microsoft Windows [Version 6.1.7600]

**Comment by vertiginous** [comment]
You have to provide a path to the pik_install command.  The ruby path is a bad choice, because pik is designed to remove the ruby path from %PATH%.

I have modified pik_install to display a nice error message when no path is provided, and to check that the path provided is in %PATH%.  

Fixed in 97835f4fe781c4b49ac6
